name: 'MyApp File Security'
author: 'MyApp Inc.'
description: 'Secure repository backup and restoration with military-grade encryption'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  activation_code:
    description: 'API activation code'
    required: true
  encryption_password:
    description: 'Encryption key (min 32 characters)'
    required: true
  action-type:
    description: 'Select operation type (backup or restore)'
    required: false
    default: 'backup'
  file_version_id:
    description: 'Required for restore operations'
    required: false
    default: ''
  restore_github_token:
    description: 'Optional token for workflow restoration'
    required: false
    default: ''
  otp_request_type:
    description: 'OTP delivery method (MAIL or AUTHENTICATOR)'
    required: false
    default: 'MAIL'

runs:
  using: 'composite'
  steps:

    - name: Validate action type
      shell: bash
      run: |
        if [[ "${{ inputs.action-type }}" != "backup" && "${{ inputs.action-type }}" != "restore" ]]; then
          echo "::error ::Invalid action-type. Must be 'backup' or 'restore'"
          exit 1
        fi

    - name: Set execute permissions
      shell: bash
      run: chmod -R +x ${{ github.action_path }}/scripts

    - name: Run Shield Backup
      if: ${{ inputs.action-type == 'backup' }}
      uses: ${{ github.action_path }}/shield
      with:
        activation_code: ${{ inputs.activation_code }}
        encryption_password: ${{ inputs.encryption_password }}
        
    - name: Run Restore
      if: ${{ inputs.action-type == 'restore' }}
      uses: ${{ github.action_path }}/restore
      with:
        activation_code: ${{ inputs.activation_code }}
        encryption_password: ${{ inputs.encryption_password }}
        file_version_id: ${{ inputs.file_version_id }}
        restore_github_token: ${{ inputs.restore_github_token }}
        otp_request_type: ${{ inputs.otp_request_type }}
