name: 'MyApp shield1 Action'
description: 'Repository mirror backup with ZSTD compression and API upload'
branding:
  icon: 'archive'
  color: 'blue'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_password:
    description: 'Secret key for encrypting backup (min. 32 chars)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set global variables
      shell: bash
      run: ${{ github.action_path }}/scripts/common/set_globals.sh

    - name: Validate encryption password
      shell: bash
      run: ${{ github.action_path }}/scripts/common/validate_password.sh
      env:
        ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}

    - name: Create mirror clone
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/mirror_clone.sh

    - name: Install dependencies
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/install_deps.sh

    - name: Compress repository
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/compress_repo.sh
      
    - name: Encrypt repository
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/encrypt_repo.sh
      env:
        ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}
        
    - name: Get activation token
      shell: bash
      run: ${{ github.action_path }}/scripts/common/get_token.sh
      env:
        ACTIVATION_CODE: ${{ inputs.activation_code }}

    - name: Upload backup
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/upload_backup.sh

    - name: Print summary
      shell: bash
      run: ${{ github.action_path }}/scripts/shield/print_summary.sh