name: 'Repository Restore'
description: 'Restores backup using OTP and file version ID'
branding:
  icon: 'package'
  color: 'green'

inputs:
  activation_code:
    description: 'Activation code for API'
    required: true
  encryption_password:
    description: 'Secret key for decrypting backup'
    required: true
  file_version_id:
    description: 'FILE_VERSION_ID for specific backup'
    required: true
  restore_github_token:
    description: 'Optional: Token for workflow restoration'
    required: false
    default: ''
  otp_request_type:
    description: 'OTP delivery method (MAIL or AUTHENTICATOR)'
    required: false
    default: 'MAIL'

runs:
  using: 'composite'
  steps:

    - name: Set global variables
      shell: bash
      run: ../scripts/common/set_globals.sh

    - name: Validate password
      shell: bash
      run: ../scripts/common/validate_password.sh
      env:
        ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get activation token
      shell: bash
      run: ../scripts/common/get_token.sh
      env:
        ACTIVATION_CODE: ${{ inputs.activation_code }}

    - name: Request OTP
      shell: bash
      run: ../scripts/restore/request_otp.sh
      env:
        OTP_TYPE: ${{ inputs.otp_request_type }}

    - name: Verify OTP
      shell: bash
      run: ../scripts/restore/verify_otp.sh

    - name: Retrieve backup
      shell: bash
      run: ../scripts/restore/retrieve_backup.sh
      env:
        FILE_VERSION_ID: ${{ inputs.file_version_id }}

    - name: Decrypt backup
      shell: bash
      run: ../scripts/restore/decrypt_backup.sh
      env:
        ENCRYPTION_PASSWORD: ${{ inputs.encryption_password }}
        
    - name: Extract backup
      shell: bash
      run: ../scripts/restore/extract_backup.sh

    - name: Configure and push
      shell: bash
      run: ../scripts/restore/configure_push.sh
      env:
        RESTORE_TOKEN: ${{ inputs.restore_github_token }}